### PR TITLE
Fixes button crash.

### PR DESCRIPTION
**Pull request by NoSharp**
Just added a little something to prevent the button crash.

### CODE REVIEW

**Comment by sarahsturgeon** [comment]
Is this something that affects all of GMod, or is it only an issue when combined with APG features?

**Comment by NoSharp** [comment]
It affects Gmod.

**Comment by NanoAi** [comment]
This "fix" just breaks being able to no-collide stuff. Probably not a good idea.

**Comment by sarahsturgeon** [comment]
If it affects all of Gmod, this addon probably isn't the right place to put it.

**Pull request closed without merging**
